variables:
  LOCAL_PATH: "/home/gitlab-runner/projects/mein-object"

before_script:
  - cp -rf .env $LOCAL_PATH/.env
  - cp -rf $LOCAL_PATH/.signing android/.signing
  - cp -rf $LOCAL_PATH/.env .env
  - export $(cat .env | grep FIREBASE_TOKEN)
  - npm cache clean --force
  - npm install

after_script:
  - rm -rf android/.signing

stages:
  - deploy_prod_android
  - deploy_stage_android

android_deploy_prod_release:
  stage: deploy_prod_android
  tags:
    - shell
  artifacts:
    paths:
      - android/app/build/outputs/apk/prod/release
  script:
    - react-native bundle 
                      --platform android 
                      --dev false 
                      --entry-file index.js 
                      --bundle-output android/app/src/main/assets/index.android.bundle 
                      --assets-dest android/app/src/main/res
    - rm -rf android/app/src/main/res/drawable-*
    - cd android && ./gradlew app:clean app:assembleProdRelease appDistributionUploadProdRelease
  when: manual

android_deploy_stage_release:
  stage: deploy_stage_android
  tags:
    - shell
  artifacts:
    paths:
      - android/app/build/outputs/apk/stage/release
  script:
    - react-native bundle 
                      --platform android 
                      --dev false 
                      --entry-file index.js 
                      --bundle-output android/app/src/main/assets/index.android.bundle 
                      --assets-dest android/app/src/main/res
    - rm -rf android/app/src/main/res/drawable-*
    - cd android && ./gradlew app:clean app:assembleStageRelease appDistributionUploadStageRelease
  when: manual