
export const chatsTypes = {
    CHATS_LOADED: 'CHATS_LOADED',
};

export const settingsTypes = {
    SETTINGS_LOADED: 'SETTINGS_LOADED',
    PLAN_UPDATE: 'PLAN_UPDATE',
    TOUR_LOADED: 'TOUR_LOADED'
};
export const voteTypes = {
    VOTE_UPDATE: 'VOTE_UPDATE',
    VOTE_CREATED: 'VOTE_CREATED',
    VOTE_LOADED:'VOTE_LOADED'
};

export const userTypes = {
    USER_LOADED: 'USER_LOADED',
    USER_UPDATE: 'USER_UPDATE',
    CHATS_LOADED: 'CHATS_LOADED',
    CHAT_CREATED: 'CHAT_CREATED',
    CHAT_UPDATE: 'CHAT_UPDATE',
    COLLECTIONS_LOADED: 'COLLECTIONS_LOADED',
    COLLECTION_CREATED: 'COLLECTION_CREATED',
    SET_CURRENT_SEMANTIC_RELATIONS: 'SET_CURRENT_SEMANTIC_RELATIONS',
};

export const museumsTypes = {
    MUSEUMS_LOADED: 'MUSEUMS_LOADED',
    MUSEUMS_UPDATE: 'MUSEUMS_UPDATE',
    CATEGORIES_LOADED: 'CATEGORIES_LOADED',
    CATEGORIES_UPDATE: 'CATEGORIES_UPDATE',
    OBJECTS_LOADED: 'OBJECTS_LOADED',
    OBJECTS_UPDATE: 'OBJECTS_UPDATE',
    OBJECT_LOADED:'OBJECT_LOADED'
}